services:
  front:
    build:
      context: ./frontend
    ports:
      - "5081:3000"
    environment:
      - FRONTEND_URL=https://clip.grzegorzkoperwas.site/
      - API_URL=http://cliper
  cliper:
    build:
      context: ./backend
    ports:
      - "5082:80"
    environment:
      - OPENAI_KEY=foo


